/* eslint quotes: 0, no-unused-vars: 0 */
/*global systemDictionary:true */
'use strict';

const _systemDictionary = {
	"security-alert adapter settings": {
		"en": "security-alert adapter settings",
		"de": "Einstellungen des Sicherheitsalarmadapters",
		"ru": "настройки адаптера системы безопасности",
		"pt": "configurações do adaptador de alerta de segurança",
		"nl": "instellingen voor beveiligingswaarschuwingsadapter",
		"fr": "paramètres de l'adaptateur d'alerte de sécurité",
		"it": "impostazioni dell'adattatore degli avvisi di sicurezza",
		"es": "configuración del adaptador de alerta de seguridad",
		"pl": "ustawienia adaptera alertów zabezpieczeń",
		"zh-cn": "安全警报适配器设置"
	},
	"Alarm settings": {
		"en": "Alarm settings",
		"de": "Alarmeinstellungen",
		"ru": "Настройки будильника",
		"pt": "Configurações de alarme",
		"nl": "Alarm instellingen",
		"fr": "Paramètres d'alarme",
		"it": "Impostazioni di allarme",
		"es": "Configuraciones de alarma",
		"pl": "Ustawienia alarmu",
		"zh-cn": "闹铃设定"
	},
	"Alexa messages": {
		"en": "Alexa messages",
		"de": "Alexa Nachrichten",
		"ru": "Сообщения Alexa",
		"pt": "Mensagens Alexa",
		"nl": "Alexa-berichten",
		"fr": "Messages Alexa",
		"it": "Messaggi di Alexa",
		"es": "Mensajes de Alexa",
		"pl": "Wiadomości Alexa",
		"zh-cn": "Alexa消息"
	},
	"AWTRIX messages": {
		"en": "AWTRIX messages",
		"de": "AWTRIX Nachrichten",
		"ru": "Сообщения AWTRIX",
		"pt": "Mensagens AWTRIX",
		"nl": "AWTRIX berichten",
		"fr": "Messages AWTRIX",
		"it": "Messaggi AWTRIX",
		"es": "Mensajes AWTRIX",
		"pl": "Wiadomości AWTRIX",
		"zh-cn": "AWTRIX讯息"
	},
	"Notifications": {
		"en": "Notifications",
		"de": "Benachrichtigungen",
		"ru": "Уведомления",
		"pt": "Notificações",
		"nl": "Meldingen",
		"fr": "Notifications",
		"it": "Notifiche",
		"es": "Notificaciones",
		"pl": "Powiadomienia",
		"zh-cn": "通知事项"
	},
	"Alarm siren": {
		"en": "Alarm siren",
		"de": "Alarmsirene",
		"ru": "Сирена сигнализации",
		"pt": "Sirene de alarme",
		"nl": "Alarmsirene",
		"fr": "Sirène d'alarme",
		"it": "Sirena d'allarme",
		"es": "Sirena de alarma",
		"pl": "Syrena alarmowa",
		"zh-cn": "警报器"
	},
	"Siren on": {
		"en": "Siren on",
		"de": "Sirene an",
		"ru": "Сирена включена",
		"pt": "Sirene ligada",
		"nl": "Sirene aan",
		"fr": "Sirène allumée",
		"it": "Sirena accesa",
		"es": "Sirena encendida",
		"pl": "Syrena włączona",
		"zh-cn": "警笛声"
	},
	"Siren off": {
		"en": "Siren off",
		"de": "Sirene aus",
		"ru": "Сирена выключена",
		"pt": "Sirene desligada",
		"nl": "Sirene uit",
		"fr": "Sirène éteinte",
		"it": "Sirena spenta",
		"es": "Sirena apagada",
		"pl": "Wyłącz syrenę",
		"zh-cn": "警笛声"
	},
	"Intruder alarm on": {
		"en": "Intruder alarm on",
		"de": "Einbruchalarm ein",
		"ru": "Включена охранная сигнализация",
		"pt": "Alarme de intruso ativado",
		"nl": "Inbraakalarm aan",
		"fr": "Alarme intrusion activée",
		"it": "Allarme intruso attivo",
		"es": "Alarma de intrusión activada",
		"pl": "Alarm włamaniowy włączony",
		"zh-cn": "入侵者警报开启"
	},
	"Intruder alarm off": {
		"en": "Intruder alarm off",
		"de": "Einbruchalarm aus",
		"ru": "Охранная сигнализация выключена",
		"pt": "Alarme de intruso desligado",
		"nl": "Inbraakalarm uit",
		"fr": "Alarme intrusion désactivée",
		"it": "Allarme intruso disattivato",
		"es": "Alarma de intrusión desactivada",
		"pl": "Alarm włamaniowy wyłączony",
		"zh-cn": "入侵者警报关闭"
	},
	"Delay for alert on": {
		"en": "Delay for alert on",
		"de": "Verzögerung für Alarm ein",
		"ru": "Задержка оповещения на",
		"pt": "Atraso para alerta em",
		"nl": "Vertraging voor alarm aan",
		"fr": "Délai d'alerte sur",
		"it": "Ritardo per avviso attivo",
		"es": "Retraso de alerta en",
		"pl": "Opóźnienie włączenia alarmu",
		"zh-cn": "警报延迟"
	},
	"Delay for hazard alerts": {
		"en": "Delay for hazard alerts",
		"de": "Verzögerung für Warnmeldungen",
		"ru": "Задержка предупреждений об опасности",
		"pt": "Atraso para alertas de perigo",
		"nl": "Vertraging voor gevarenwaarschuwingen",
		"fr": "Délai pour les alertes de danger",
		"it": "Ritardo per gli avvisi di pericolo",
		"es": "Retraso de las alertas de peligro",
		"pl": "Opóźnienie dla alertów o zagrożeniach",
		"zh-cn": "延迟危险警报"
	},
	"Sensor categories / groups": {
		"en": "Sensor categories / groups",
		"de": "Sensorkategorien / -gruppen",
		"ru": "Категории / группы датчиков",
		"pt": "Categorias / grupos de sensores",
		"nl": "Sensor categorieën / groepen",
		"fr": "Catégories / groupes de capteurs",
		"it": "Categorie / gruppi di sensori",
		"es": "Categorías / grupos de sensores",
		"pl": "Kategorie / grupy czujników",
		"zh-cn": "传感器类别/组"
	},
	"Category (enum) for alerts": {
		"en": "Category (enum) for alerts",
		"de": "Kategorie (Aufzählung) für Warnungen",
		"ru": "Категория (перечисление) для предупреждений",
		"pt": "Categoria (enum) para alertas",
		"nl": "Categorie (enum) voor waarschuwingen",
		"fr": "Catégorie (énumération) pour les alertes",
		"it": "Categoria (enum) per gli avvisi",
		"es": "Categoría (enumeración) para alertas",
		"pl": "Kategoria (wyliczenie) dla alertów",
		"zh-cn": "警报的类别（枚举）"
	},
	"add": {
		"en": "add",
		"de": "hinzufügen",
		"ru": "Добавить",
		"pt": "adicionar",
		"nl": "toevoegen",
		"fr": "ajouter",
		"it": "Inserisci",
		"es": "añadir",
		"pl": "Dodaj",
		"zh-cn": "加"
	},
	"Group": {
		"en": "Group",
		"de": "Gruppe",
		"ru": "Группа",
		"pt": "Grupo",
		"nl": "Groep",
		"fr": "Groupe",
		"it": "Gruppo",
		"es": "Grupo",
		"pl": "Grupa",
		"zh-cn": "组"
	},
	"Value": {
		"en": "Value",
		"de": "Wert",
		"ru": "Ценность",
		"pt": "Valor",
		"nl": "Waarde",
		"fr": "Valeur",
		"it": "Valore",
		"es": "Valor",
		"pl": "Wartość",
		"zh-cn": "值"
	},
	"Category": {
		"en": "Category",
		"de": "Kategorie",
		"ru": "Категория",
		"pt": "Categoria",
		"nl": "Categorie",
		"fr": "Catégorie",
		"it": "Categoria",
		"es": "Categoría",
		"pl": "Kategoria",
		"zh-cn": "类别"
	},
	"Type": {
		"en": "Type",
		"de": "Art",
		"ru": "Тип",
		"pt": "Tipo",
		"nl": "Type",
		"fr": "Type",
		"it": "genere",
		"es": "Tipo",
		"pl": "Rodzaj",
		"zh-cn": "类型"
	},
	"Siren": {
		"en": "Siren",
		"de": "Sirene",
		"ru": "Сирена",
		"pt": "Sereia",
		"nl": "Sirene",
		"fr": "Sirène",
		"it": "Sirena",
		"es": "Sirena",
		"pl": "Syrena",
		"zh-cn": "警笛"
	},
	"Message text": {
		"en": "Message text",
		"de": "Nachrichtentext",
		"ru": "Текст сообщения",
		"pt": "Mensagem de texto",
		"nl": "Bericht tekst",
		"fr": "Texte du message",
		"it": "Messaggio di testo",
		"es": "Mensaje de texto",
		"pl": "Wiadomość tekstowa",
		"zh-cn": "讯息文字"
	},
	"Notification": {
		"en": "Notification",
		"de": "Benachrichtigung",
		"ru": "Уведомление",
		"pt": "Notificação",
		"nl": "Kennisgeving",
		"fr": "Notification",
		"it": "Notifica",
		"es": "Notificación",
		"pl": "Powiadomienie",
		"zh-cn": "通知"
	},
	"Volume for messages": {
		"en": "Volume for messages",
		"de": "Lautstärke für Nachrichten",
		"ru": "Объем сообщений",
		"pt": "Volume para mensagens",
		"nl": "Volume voor berichten",
		"fr": "Volume des messages",
		"it": "Volume per i messaggi",
		"es": "Volumen de mensajes",
		"pl": "Głośność wiadomości",
		"zh-cn": "留言量"
	},
	"Standard volume": {
		"en": "Standard volume",
		"de": "Standardvolumen",
		"ru": "Стандартный объем",
		"pt": "Volume padrão",
		"nl": "Standaardvolume",
		"fr": "Volume standard",
		"it": "Volume standard",
		"es": "Volumen estándar",
		"pl": "Standardowa objętość",
		"zh-cn": "标准体积"
	},
	"Alexa speaks": {
		"en": "Alexa speaks",
		"de": "Alexa spricht",
		"ru": "Алекса говорит",
		"pt": "Alexa fala",
		"nl": "Alexa spreekt",
		"fr": "Alexa parle",
		"it": "Alexa parla",
		"es": "Alexa habla",
		"pl": "Alexa mówi",
		"zh-cn": "Alexa讲话"
	},
	"Repeat message": {
		"en": "Repeat message",
		"de": "Nachricht wiederholen",
		"ru": "Повторить сообщение",
		"pt": "Repita a mensagem",
		"nl": "Herhaal bericht",
		"fr": "Répéter le message",
		"it": "Ripeti il messaggio",
		"es": "Repetir mensaje",
		"pl": "Powtórz wiadomość",
		"zh-cn": "重复留言"
	},
	"Volume": {
		"en": "Volume",
		"de": "Volumen",
		"ru": "Объем",
		"pt": "Volume",
		"nl": "Volume",
		"fr": "Le volume",
		"it": "Volume",
		"es": "Volumen",
		"pl": "Tom",
		"zh-cn": "卷"
	},
	"AWTRIX message": {
		"en": "AWTRIX message",
		"de": "AWTRIX-Nachricht",
		"ru": "Сообщение AWTRIX",
		"pt": "Mensagem AWTRIX",
		"nl": "AWTRIX-bericht",
		"fr": "Message AWTRIX",
		"it": "Messaggio AWTRIX",
		"es": "Mensaje AWTRIX",
		"pl": "Wiadomość AWTRIX",
		"zh-cn": "AWTRIX讯息"
	},
	"Force": {
		"en": "force",
		"de": "erzwingen",
		"ru": "сила",
		"pt": "força",
		"nl": "dwingen",
		"fr": "Obliger",
		"it": "vigore",
		"es": "fuerza",
		"pl": "siła",
		"zh-cn": "力"
	},
	"Lifetime": {
		"en": "Lifetime",
		"de": "Lebenszeit",
		"ru": "Продолжительность жизни",
		"pt": "Vida",
		"nl": "Levenslang",
		"fr": "Durée de vie",
		"it": "Tutta la vita",
		"es": "Toda la vida",
		"pl": "Dożywotni",
		"zh-cn": "寿命"
	},
	"Sound": {
		"en": "Sound",
		"de": "Klang",
		"ru": "Звук",
		"pt": "Som",
		"nl": "Geluid",
		"fr": "Du son",
		"it": "Suono",
		"es": "Sonido",
		"pl": "Dźwięk",
		"zh-cn": "声音"
	},
	"Icon": {
		"en": "Icon",
		"de": "Symbol",
		"ru": "Икона",
		"pt": "Ícone",
		"nl": "Icoon",
		"fr": "Icône",
		"it": "Icona",
		"es": "Icono",
		"pl": "Ikona",
		"zh-cn": "图标"
	},
	"move icon": {
		"en": "move icon",
		"de": "Symbol verschieben",
		"ru": "значок перемещения",
		"pt": "ícone de movimento",
		"nl": "pictogram verplaatsen",
		"fr": "icône de déplacement",
		"it": "icona di spostamento",
		"es": "mover icono",
		"pl": "ikonę przenoszenia",
		"zh-cn": "移动图标"
	},
	"color": {
		"en": "color",
		"de": "Farbe",
		"ru": "цвет",
		"pt": "cor",
		"nl": "kleur",
		"fr": "Couleur",
		"it": "colore",
		"es": "color",
		"pl": "kolor",
		"zh-cn": "颜色"
	},
	"Telegram": {
		"en": "Telegram",
		"de": "Telegramm",
		"ru": "Телеграмма",
		"pt": "Telegrama",
		"nl": "Telegram",
		"fr": "Télégramme",
		"it": "Telegramma",
		"es": "Telegrama",
		"pl": "Telegram",
		"zh-cn": "电报"
	},
	"E-Mail": {
		"en": "E-Mail",
		"de": "Email",
		"ru": "Эл. почта",
		"pt": "O email",
		"nl": "E-mail",
		"fr": "Email",
		"it": "E-mail",
		"es": "Correo electrónico",
		"pl": "E-mail",
		"zh-cn": "电子邮件"
	},
	"Pushover": {
		"en": "Pushover",
		"de": "Pushover",
		"ru": "Пустышка",
		"pt": "Pushover",
		"nl": "Pushover",
		"fr": "Pushover",
		"it": "Pushover",
		"es": "Persona fácil de convencer",
		"pl": "Łatwizna",
		"zh-cn": "前推"
	},
	"WhatsApp": {
		"en": "WhatsApp",
		"de": "WhatsApp",
		"ru": "WhatsApp",
		"pt": "Whatsapp",
		"nl": "WhatsApp",
		"fr": "WhatsApp",
		"it": "WhatsApp",
		"es": "WhatsApp",
		"pl": "WhatsApp",
		"zh-cn": "WhatsApp的"
	},
	"notifications type": {
		"en": "notifications type",
		"de": "Benachrichtigungstyp",
		"ru": "тип уведомлений",
		"pt": "tipo de notificações",
		"nl": "type meldingen",
		"fr": "type de notifications",
		"it": "tipo di notifiche",
		"es": "tipo de notificaciones",
		"pl": "typ powiadomień",
		"zh-cn": "通知类型"
	},
	"Alexa": {
		"en": "Alexa",
		"de": "Alexa",
		"ru": "Алекса",
		"pt": "Alexa",
		"nl": "Alexa",
		"fr": "Alexa",
		"it": "Alexa",
		"es": "Alexa",
		"pl": "Alexa",
		"zh-cn": "亚历克斯"
	},
	"AWTRIX": {
		"en": "AWTRIX",
		"de": "AWTRIX",
		"ru": "AWTRIX",
		"pt": "AWTRIX",
		"nl": "AWTRIX",
		"fr": "AWTRIX",
		"it": "AWTRIX",
		"es": "AWTRIX",
		"pl": "AWTRIX",
		"zh-cn": "AWTRIX"
	},
	"Telegram instance": {
		"en": "Telegram instance",
		"de": "Telegramminstanz",
		"ru": "Экземпляр Telegram",
		"pt": "Instância de telegrama",
		"nl": "Telegram-instantie",
		"fr": "Instance de télégramme",
		"it": "Istanza di Telegram",
		"es": "Instancia de Telegram",
		"pl": "Instancja telegramu",
		"zh-cn": "电报实例"
	},
	"Telegram Receiver": {
		"en": "Telegram Receiver",
		"de": "Telegrammempfänger",
		"ru": "Получатель Telegram",
		"pt": "Receptor de telegrama",
		"nl": "Telegram-ontvanger",
		"fr": "Récepteur de télégramme",
		"it": "Ricevitore di Telegram",
		"es": "Receptor de telegramas",
		"pl": "Odbiornik telegramu",
		"zh-cn": "电报接收器"
	},
	"Silent Notice": {
		"en": "Silent Notice",
		"de": "Stille Nachricht",
		"ru": "Тихое уведомление",
		"pt": "Aviso Silencioso",
		"nl": "Stille kennisgeving",
		"fr": "Avis silencieux",
		"it": "Avviso silenzioso",
		"es": "Aviso silencioso",
		"pl": "Cicha uwaga",
		"zh-cn": "静默通知"
	},
	"WhatsApp instance": {
		"en": "WhatsApp instance",
		"de": "WhatsApp-Instanz",
		"ru": "Экземпляр WhatsApp",
		"pt": "Instância WhatsApp",
		"nl": "WhatsApp-instantie",
		"fr": "Instance WhatsApp",
		"it": "Istanza WhatsApp",
		"es": "Instancia de WhatsApp",
		"pl": "Instancja WhatsApp",
		"zh-cn": "WhatsApp实例"
	},
	"Pushover instance": {
		"en": "Pushover instance",
		"de": "Pushover-Instanz",
		"ru": "Экземпляр Pushover",
		"pt": "Instância pushover",
		"nl": "Pushover-instantie",
		"fr": "Instance pushover",
		"it": "Istanza di pushover",
		"es": "Instancia de empuje",
		"pl": "Instancja pushover",
		"zh-cn": "Pushover实例"
	},
	"device ID (optional)": {
		"en": "device ID (optional)",
		"de": "Geräte-ID (optional)",
		"ru": "ID устройства (необязательно)",
		"pt": "ID do dispositivo (opcional)",
		"nl": "apparaat-ID (optioneel)",
		"fr": "ID de l'appareil (facultatif)",
		"it": "ID dispositivo (opzionale)",
		"es": "ID de dispositivo (opcional)",
		"pl": "identyfikator urządzenia (opcjonalnie)",
		"zh-cn": "设备ID（可选）"
	},
	"sound (optional)": {
		"en": "sound (optional)",
		"de": "Ton (optional)",
		"ru": "звук (необязательно)",
		"pt": "som (opcional)",
		"nl": "geluid (optioneel)",
		"fr": "son (facultatif)",
		"it": "suono (opzionale)",
		"es": "sonido (opcional)",
		"pl": "dźwięk (opcjonalnie)",
		"zh-cn": "声音（可选）"
	},
	"Priority": {
		"en": "Priority",
		"de": "Priorität",
		"ru": "Приоритет",
		"pt": "Prioridade",
		"nl": "Prioriteit",
		"fr": "Priorité",
		"it": "Priorità",
		"es": "Prioridad",
		"pl": "Priorytet",
		"zh-cn": "优先"
	},
	"email receiver": {
		"en": "email receiver",
		"de": "E-Mail-Empfänger",
		"ru": "получатель электронной почты",
		"pt": "receptor de email",
		"nl": "e-mailontvanger",
		"fr": "récepteur de courrier électronique",
		"it": "destinatario di posta elettronica",
		"es": "receptor de correo electrónico",
		"pl": "odbiorca poczty elektronicznej",
		"zh-cn": "电子邮件接收者"
	},
	"email sender": {
		"en": "email sender",
		"de": "E-Mail-Absender",
		"ru": "отправитель электронной почты",
		"pt": "remetente de email",
		"nl": "e-mail afzender",
		"fr": "expéditeur de l'e-mail",
		"it": "mittente di posta elettronica",
		"es": "remitente de correo electrónico",
		"pl": "nadawca wiadomości e-mail",
		"zh-cn": "电子邮件发件人"
	},
	"email instance": {
		"en": "email instance",
		"de": "E-Mail-Instanz",
		"ru": "экземпляр электронной почты",
		"pt": "instância de email",
		"nl": "e-mailinstantie",
		"fr": "instance de messagerie",
		"it": "istanza di posta elettronica",
		"es": "instancia de correo electrónico",
		"pl": "wystąpienie poczty e-mail",
		"zh-cn": "电子邮件实例"
	},
	"Allgemeine Einstellungen": {
		"en": "Allgemeine Einstellungen",
		"de": "Allgemeine Einstellungen",
		"ru": "Allgemeine Einstellungen",
		"pt": "Allgemeine Einstellungen",
		"nl": "Allgemeine Einstellungen",
		"fr": "Allgemeine Einstellungen",
		"it": "Allgemeine Einstellungen",
		"es": "Allgemeine Einstellungen",
		"pl": "Allgemeine Einstellungen",
		"zh-cn": "蛋氨酸"
	},
	"Long Notifications": {
		"en": "Long Notifications",
		"de": "Lange Benachrichtigungen",
		"ru": "Длинные уведомления",
		"pt": "Notificações longas",
		"nl": "Lange meldingen",
		"fr": "Notifications longues",
		"it": "Notifiche lunghe",
		"es": "Notificaciones largas",
		"pl": "Długie powiadomienia",
		"zh-cn": "长通知"
	},
	"Short Notifications": {
		"en": "Short Notifications",
		"de": "Kurze Benachrichtigungen",
		"ru": "Короткие уведомления",
		"pt": "Notificações curtas",
		"nl": "Korte meldingen",
		"fr": "Notifications courtes",
		"it": "Notifiche brevi",
		"es": "Notificaciones breves",
		"pl": "Krótkie powiadomienia",
		"zh-cn": "简短通知"
	},
	"Notification Style": {
		"en": "Notification Style",
		"de": "Benachrichtigungsstil",
		"ru": "Уведомление Стиль",
		"pt": "Estilo de Notificação",
		"nl": "Meldingsstijl",
		"fr": "Style de notification",
		"it": "Stile di notifica",
		"es": "Estilo de notificación",
		"pl": "Styl powiadomienia",
		"zh-cn": "通知样式"
	},
	"no notifications": {
		"en": "no notifications",
		"de": "keine Benachrichtigungen",
		"ru": "нет уведомлений",
		"pt": "nenhuma notificação",
		"nl": "geen notificaties",
		"fr": "aucune notification",
		"it": "nessuna notifica",
		"es": "no Notificaciones",
		"pl": "brak powiadomień",
		"zh-cn": "没有通知"
	},
	"informations": {
		"en": "informations",
		"de": "Informationen",
		"ru": "информация",
		"pt": "informações",
		"nl": "informatie",
		"fr": "informations",
		"it": "informazioni",
		"es": "informaciones",
		"pl": "informacje",
		"zh-cn": "资讯"
	},
	"informations, warnings": {
		"en": "informations, warnings",
		"de": "Informationen, Warnungen",
		"ru": "информация, предупреждения",
		"pt": "informações, avisos",
		"nl": "informatie, waarschuwingen",
		"fr": "informations, avertissements",
		"it": "informazioni, avvertenze",
		"es": "informaciones, advertencias",
		"pl": "informacje, ostrzeżenia",
		"zh-cn": "信息，警告"
	},
	"informations, errors": {
		"en": "informations, errors",
		"de": "Informationen, Fehler",
		"ru": "информация, ошибки",
		"pt": "informações, erros",
		"nl": "informatie, fouten",
		"fr": "informations, erreurs",
		"it": "informazioni, errori",
		"es": "informaciones, errores",
		"pl": "informacje, błędy",
		"zh-cn": "信息，错误"
	},
	"informations, warnings, errors": {
		"en": "informations, warnings, errors",
		"de": "Informationen, Warnungen, Fehler",
		"ru": "информация, предупреждения, ошибки",
		"pt": "informações, avisos, erros",
		"nl": "informatie, waarschuwingen, fouten",
		"fr": "informations, avertissements, erreurs",
		"it": "informazioni, avvisi, errori",
		"es": "información, advertencias, errores",
		"pl": "informacje, ostrzeżenia, błędy",
		"zh-cn": "信息，警告，错误"
	},
	"warnings": {
		"en": "warnings",
		"de": "Warnungen",
		"ru": "предупреждения",
		"pt": "avisos",
		"nl": "waarschuwingen",
		"fr": "avertissements",
		"it": "avvertenze",
		"es": "advertencias",
		"pl": "ostrzeżenia",
		"zh-cn": "警告"
	},
	"warnings, errors": {
		"en": "warnings, errors",
		"de": "Warnungen, Fehler",
		"ru": "предупреждения, ошибки",
		"pt": "avisos, erros",
		"nl": "waarschuwingen, fouten",
		"fr": "avertissements, erreurs",
		"it": "avvertenze, errori",
		"es": "advertencias, errores",
		"pl": "ostrzeżenia, błędy",
		"zh-cn": "警告，错误"
	},
	"errors": {
		"en": "errors",
		"de": "Fehler",
		"ru": "ошибки",
		"pt": "erros",
		"nl": "fouten",
		"fr": "les erreurs",
		"it": "errori",
		"es": "errores",
		"pl": "błędy",
		"zh-cn": "错误"
	},
	"message type": {
		"en": "message type",
		"de": "Nachrichtentyp",
		"ru": "тип сообщения",
		"pt": "tipo de mensagem",
		"nl": "berichttype",
		"fr": "type de message",
		"it": "tipo di messaggio",
		"es": "Tipo de mensaje",
		"pl": "typ wiadomości",
		"zh-cn": "讯息类型"
	},
	"Waiting for the send (seconds)": {
		"en": "Waiting for the send (seconds)",
		"de": "Warten auf den Versand (Sekunden)",
		"ru": "Ожидание отправки (секунды)",
		"pt": "Esperando pelo envio (segundos)",
		"nl": "Wachten op verzending (seconden)",
		"fr": "En attente de l'envoi (secondes)",
		"it": "Aspettando l'invio (secondi)",
		"es": "Esperando el envío (segundos)",
		"pl": "Oczekiwanie na wysłanie (sekundy)",
		"zh-cn": "等待发送（秒）"
	},
	"Fire in the house! Leave your home immediately!": {
		"en": "Fire in the house! Leave your home immediately!",
		"de": "Feuer im Haus! Verlasse sofort dein Zuhause!",
		"ru": "Пожар в доме! Немедленно покиньте свой дом!",
		"pt": "Fogo na casa! Saia de casa imediatamente!",
		"nl": "Brand in huis! Verlaat onmiddellijk uw huis!",
		"fr": "Feu dans la maison! Quittez votre maison immédiatement!",
		"it": "Fuoco in casa! Lascia subito la tua casa!",
		"es": "¡Fuego en la casa! ¡Sal de tu casa inmediatamente!",
		"pl": "Ogień w domu! Natychmiast opuść swój dom!",
		"zh-cn": "在房子里开火！立即离开家！"
	},
	"Gas leak in the house! Leave your home immediately!": {
		"en": "Gas leak in the house! Leave your home immediately!",
		"de": "Gasleck im Haus! Verlasse sofort dein Zuhause!",
		"ru": "Утечка газа в доме! Немедленно покиньте свой дом!",
		"pt": "Vazamento de gás na casa! Saia de casa imediatamente!",
		"nl": "Gaslek in huis! Verlaat onmiddellijk uw huis!",
		"fr": "Fuite de gaz dans la maison! Quittez votre maison immédiatement!",
		"it": "Perdita di gas in casa! Lascia subito la tua casa!",
		"es": "¡Fuga de gas en la casa! ¡Sal de tu casa inmediatamente!",
		"pl": "Wyciek gazu w domu! Natychmiast opuść swój dom!",
		"zh-cn": "屋子里有煤气泄漏！立即离开家！"
	},
	"Carbon monoxide in the house! Leave your home immediately!": {
		"en": "Carbon monoxide in the house! Leave your home immediately!",
		"de": "Kohlenmonoxid im Haus! Verlasse sofort dein Zuhause!",
		"ru": "Окись углерода в доме! Немедленно покиньте свой дом!",
		"pt": "Monóxido de carbono em casa! Saia de casa imediatamente!",
		"nl": "Koolmonoxide in huis! Verlaat onmiddellijk uw huis!",
		"fr": "Monoxyde de carbone dans la maison! Quittez votre maison immédiatement!",
		"it": "Monossido di carbonio in casa! Lascia subito la tua casa!",
		"es": "¡Monóxido de carbono en la casa! ¡Sal de tu casa inmediatamente!",
		"pl": "Tlenek węgla w domu! Natychmiast opuść swój dom!",
		"zh-cn": "一氧化碳在房子里！立即离开家！"
	},
	"Water ingress in the house! Close the main tap immediately!": {
		"en": "Water ingress in the house! Close the main tap immediately!",
		"de": "Wassereintritt im Haus! Schließen Sie sofort den Haupthahn!",
		"ru": "Попадание воды в дом! Немедленно закройте главный кран!",
		"pt": "Entrada de água na casa! Feche a torneira principal imediatamente!",
		"nl": "Binnendringend water in huis! Hoofdkraan direct sluiten!",
		"fr": "Entrée d'eau dans la maison! Fermez immédiatement le robinet principal!",
		"it": "Ingresso di acqua in casa! Chiudi subito il rubinetto principale!",
		"es": "¡Entrada de agua en la casa! ¡Cierre el grifo principal inmediatamente!",
		"pl": "Wnikanie wody do domu! Natychmiast zamknij główny kran!",
		"zh-cn": "房子进水！立即关闭主水龙头！"
	},
	"Vibration alarm triggered! Check immediately!": {
		"en": "Vibration alarm triggered! Check immediately!",
		"de": "Vibrationsalarm ausgelöst! Sofort prüfen!",
		"ru": "Сработала вибрационная сигнализация! Проверяйте немедленно!",
		"pt": "Alarme de vibração disparado! Verifique imediatamente!",
		"nl": "Trilalarm geactiveerd! Controleer direct!",
		"fr": "Alarme de vibration déclenchée! Vérifiez immédiatement!",
		"it": "Allarme vibrazione attivato! Controlla subito!",
		"es": "¡Alarma de vibración activada! ¡Compruebe inmediatamente!",
		"pl": "Uruchomił się alarm wibracyjny! Sprawdź natychmiast!",
		"zh-cn": "振动报警触发！立即检查！"
	},
	"Someone is trying to break into the window! Check immediately and call the police!": {
		"en": "Someone is trying to break into the window! Check immediately and call the police!",
		"de": "Jemand versucht ins Fenster einzubrechen! Überprüfen Sie sofort und rufen Sie die Polizei!",
		"ru": "Кто-то пытается взломать окно! Немедленно проверьте и вызовите полицию!",
		"pt": "Alguém está tentando arrombar a janela! Verifique imediatamente e chame a polícia!",
		"nl": "Iemand probeert in te breken door het raam! Controleer onmiddellijk en bel de politie!",
		"fr": "Quelqu'un essaie de pénétrer par la fenêtre! Vérifiez immédiatement et appelez la police!",
		"it": "Qualcuno sta cercando di entrare nella finestra! Controlla subito e chiama la polizia!",
		"es": "¡Alguien está intentando entrar por la ventana! ¡Verifique inmediatamente y llame a la policía!",
		"pl": "Ktoś próbuje włamać się do okna! Sprawdź natychmiast i wezwij policję!",
		"zh-cn": "有人试图闯入窗户！立即检查并报警！"
	},
	"Someone is trying to break in through the doors! Check immediately and call the police!": {
		"en": "Someone is trying to break in through the doors! Check immediately and call the police!",
		"de": "Jemand versucht durch die Türen einzubrechen! Überprüfen Sie sofort und rufen Sie die Polizei!",
		"ru": "Кто-то пытается прорваться через двери! Немедленно проверьте и вызовите полицию!",
		"pt": "Alguém está tentando arrombar as portas! Verifique imediatamente e chame a polícia!",
		"nl": "Iemand probeert door de deuren in te breken! Controleer onmiddellijk en bel de politie!",
		"fr": "Quelqu'un essaie de pénétrer par les portes! Vérifiez immédiatement et appelez la police!",
		"it": "Qualcuno sta cercando di entrare dalle porte! Controlla subito e chiama la polizia!",
		"es": "¡Alguien está intentando entrar por las puertas! ¡Verifique inmediatamente y llame a la policía!",
		"pl": "Ktoś próbuje włamać się przez drzwi! Sprawdź natychmiast i wezwij policję!",
		"zh-cn": "有人试图闯入大门！立即检查并报警！"
	},
	"Someone is trying to break in! Check immediately and call the police!": {
		"en": "Someone is trying to break in! Check immediately and call the police!",
		"de": "Jemand versucht einzubrechen! Überprüfen Sie sofort und rufen Sie die Polizei!",
		"ru": "Кто-то пытается ворваться! Немедленно проверьте и вызовите полицию!",
		"pt": "Alguém está tentando entrar! Verifique imediatamente e chame a polícia!",
		"nl": "Iemand probeert in te breken! Controleer onmiddellijk en bel de politie!",
		"fr": "Quelqu'un essaie de s'introduire! Vérifiez immédiatement et appelez la police!",
		"it": "Qualcuno sta cercando di entrare! Controlla subito e chiama la polizia!",
		"es": "¡Alguien está intentando entrar! ¡Verifique inmediatamente y llame a la policía!",
		"pl": "Ktoś próbuje się włamać! Sprawdź natychmiast i wezwij policję!",
		"zh-cn": "有人试图闯入！立即检查并报警！"
	},
	"A hazard alarm has struck. Leave your house immediately!": {
		"en": "A hazard alarm has struck. Leave your house immediately!",
		"de": "Ein Gefahrenalarm hat ausgelöst. Verlasse sofort dein Haus!",
		"ru": "Сработала аварийная сигнализация. Немедленно покиньте свой дом!",
		"pt": "Um alarme de perigo disparou. Saia de casa imediatamente!",
		"nl": "Er is een gevarenalarm afgegaan. Verlaat onmiddellijk uw huis!",
		"fr": "Une alarme de danger s'est déclenchée. Quittez votre maison immédiatement!",
		"it": "È scattato un allarme di pericolo. Esci subito da casa tua!",
		"es": "Ha sonado una alarma de peligro. ¡Sal de tu casa inmediatamente!",
		"pl": "Włączył się alarm ostrzegawczy. Natychmiast opuść swój dom!",
		"zh-cn": "危险警报已发出。立即离开你的房子！"
	},
	"Call security organization and leave the house": {
		"en": "Call security organization and leave the house",
		"de": "Rufen Sie die Sicherheitsorganisation an und verlassen Sie das Haus",
		"ru": "Позвоните в охранную организацию и выйдите из дома",
		"pt": "Ligue para a organização de segurança e saia de casa",
		"nl": "Bel de beveiligingsorganisatie en verlaat het huis",
		"fr": "Appelez l'organisation de sécurité et quittez la maison",
		"it": "Chiama l'organizzazione della sicurezza e esci di casa",
		"es": "Llame a la organización de seguridad y salga de la casa.",
		"pl": "Zadzwoń do organizacji ochrony i wyjdź z domu",
		"zh-cn": "致电安全组织并离开家"
	},
	"Security alert:": {
		"en": "Security alert:",
		"de": "Sicherheitsalarm:",
		"ru": "Предупреждение системы безопасности:",
		"pt": "Alerta de segurança:",
		"nl": "Beveiligingsalarm:",
		"fr": "Alerte de sécurité:",
		"it": "Allarme di sicurezza:",
		"es": "Alerta de seguridad:",
		"pl": "Alarm bezpieczeństwa:",
		"zh-cn": "安全警报："
	}
};

if (typeof module !== 'undefined' && module.parent) {
	module.exports = _systemDictionary;
} else {
	systemDictionary = _systemDictionary;
}
